apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aa0156-prod

resources:
- ../../base

images:
- name: image-registry.apps.silver.devops.gov.bc.ca/aa0156-tools/dt-moodle-apache
  newTag: prod 
patches:
  - target:
      kind: PersistentVolumeClaim
      name: backup-pvc
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: backup-pvc
      spec:
        resources:
          requests:
            storage: 2Gi
  - target:
      kind: Route
    patch: |-
      - op: replace
        path: /spec/host
        value: dt-moodle.apps.silver.devops.gov.bc.ca
  - target:
      kind: Deployment
      name: moodle-apache
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MOODLE_WWWROOT
          value: "https://dt-moodle.apps.silver.devops.gov.bc.ca"
# - target:
#     kind: Deployment
#     name: moodle-apache
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/limits/memory
#       value: 2Gi
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/limits/cpu
#       value: 1000m
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/requests/memory
#       value: 1Gi
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/requests/cpu
#       value: 500m
# - target:
#     kind: Deployment
#     name: mysql
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/limits/memory
#       value: 1Gi
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/limits/cpu
#       value: 1000m
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/requests/memory
#       value: 512Mi
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/requests/cpu
#       value: 500m

# patches:
# - target:
#     kind: Deployment
#     name: postgresql
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/limits/memory
#       value: 1Gi
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/limits/cpu
#       value: 1000m
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/requests/memory
#       value: 512Mi
#     - op: replace
#       path: /spec/template/spec/containers/0/resources/requests/cpu
#       value: 500m 
#       value: 500m 