apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: aa0156-dev

images:
- name: image-registry.apps.silver.devops.gov.bc.ca/aa0156-tools/dt-moodle-apache
  newName: image-registry.apps.silver.devops.gov.bc.ca/aa0156-tools/dt-moodle-apache
  newTag: dev 