apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-role-binding
subjects:
- kind: ServiceAccount
  name: backup-sa
roleRef:
  kind: Role
  name: backup-role
  apiGroup: rbac.authorization.k8s.io 