apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apache-config.yaml
- deployment.yaml
- mysql-secret.yaml
- mysql-deployment.yaml
- mysql-pvc.yaml
- mysql-service.yaml
- network-policy.yaml
- pvc.yaml
- route.yaml
- service.yaml
- moodle-config.yaml
- hpa.yaml
- backup-job.yaml
- backup-pvc.yaml
- backup-sa.yaml
- moodle-cron.yaml
- moodle-cron-sa.yaml
- redis-deployment.yaml
- redis-service.yaml
- redis-pvc.yaml

images:
- name: image-registry.apps.silver.devops.gov.bc.ca/aa0156-tools/dt-moodle-apache
  newName: image-registry.apps.silver.devops.gov.bc.ca/aa0156-tools/dt-moodle-apache
  newTag: latest 