apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-custom-config
data:
  config.php: |
    <?php  // Moodle configuration file

    unset($CFG);
    global $CFG;
    $CFG = new stdClass();

    $CFG->dbtype    = 'mariadb';
    $CFG->dblibrary = 'native';
    $CFG->dbhost    = getenv('MOODLE_DATABASE_HOST') ?: 'moodle-mariadb';
    $CFG->dbname    = getenv('MOODLE_DATABASE_NAME') ?: 'moodle';
    $CFG->dbuser    = getenv('MOODLE_DATABASE_USER');
    $CFG->dbpass    = getenv('MOODLE_DATABASE_PASSWORD');
    $CFG->prefix    = 'mdl_';
    $CFG->dboptions = array(
      'dbpersist' => 0,
      'dbport' => 3306,
      'dbsocket' => '',
      'dbcollation' => 'utf8mb4_unicode_ci',
    );

    // Set default HTTP_HOST if not set
    if (empty($_SERVER['HTTP_HOST'])) {
      $_SERVER['HTTP_HOST'] = '127.0.0.1:8080';
    }

    // Always use HTTPS for wwwroot when sslproxy is enabled
    $CFG->wwwroot = 'https://' . $_SERVER['HTTP_HOST'];
    $CFG->sslproxy = true;

    $CFG->dataroot = '/var/www/html/moodledata';
    $CFG->admin = 'admin';
    $CFG->directorypermissions = 02777;
    $CFG->dirroot = '/var/www/html';

    require_once(__DIR__ . '/lib/setup.php');

    // There is no php closing tag in this file,
    // it is intentional because it prevents trailing whitespace problems! 