apiVersion: batch/v1
kind: CronJob
metadata:
  name: moodle-cron
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: moodle-cron-sa
          containers:
          - name: moodle-cron
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              # Get namespace
              NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              
              # Find the Moodle pod
              MOODLE_POD=$(kubectl get pods -n $NAMESPACE -l app=moodle-apache -o jsonpath='{.items[0].metadata.name}')
              
              if [ -z "$MOODLE_POD" ]; then
                echo "Error: Moodle pod not found with label app=moodle-apache"
                exit 1
              fi
              
              echo "Found Moodle pod: $MOODLE_POD"
              
              # Execute the CLI cron script in the Moodle pod
              kubectl exec -n $NAMESPACE $MOODLE_POD -- php /var/www/html/admin/cli/cron.php
          restartPolicy: OnFailure 