apiVersion: v1
kind: ServiceAccount
metadata:
  name: moodle-cron-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: moodle-cron-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moodle-cron-rolebinding
subjects:
- kind: ServiceAccount
  name: moodle-cron-sa
roleRef:
  kind: Role
  name: moodle-cron-role
  apiGroup: rbac.authorization.k8s.io 